language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-slideshow' ]; then cd .. && eval "mv $currentfolder generator-slideshow" && cd generator-slideshow; fi

